baseURL = "https://tutorial.ponylang.io/"
DefaultContentLanguage = "en-us"
title = "Pony Tutorial"
theme = "pony-doc-site"
canonifyurls = false
preserveTaxonomyNames = true
enableGitInfo = true
uglyURLs = true

[params]
  github = "https://www.github.com/ponylang/ponyc"
  twitter = "https://www.twitter.com/ponylang"

[related]
  threshold = 80
  includeNewer = true
  toLower = false

[[related.indices]]
  name = "tags"
  weight = 100

[outputs]
  home = ["HTML", "JSON"]
  page = ["HTML"]
